In [1]:
import sys

import numpy as np

In [2]:
sys.getsizeof(5)

<IPython.core.display.Javascript object>

28

In [3]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

<IPython.core.display.Javascript object>

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a[1,0]

4

In [6]:
a[1][0]

4

In [7]:
a.sum()

45

In [8]:
a.sum(axis=1)

array([ 6, 15, 24])

Vectors

In [12]:
a = np.arange(5)
a

<IPython.core.display.Javascript object>

array([0, 1, 2, 3, 4])

In [11]:
a = a + 10
a

array([10, 11, 12, 13, 14])

In [13]:
a+=10

In [14]:
a

array([10, 11, 12, 13, 14])

In [15]:
a = np.arange(5)
b= np.arange(10,15)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [18]:
a,b

(array([0, 1, 2, 3, 4]), array([10, 11, 12, 13, 14]))

In [17]:
a+b

array([10, 12, 14, 16, 18])